name: Build and push to Docker Hub and AWS ECR

on:
  push:
    branches:
      - main
jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Update pip
        run: pip install --upgrade pip

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKERHUB_USERNAME }}
          password: ${{secrets.DOCKERHUB_TOKEN }}

      - name: Set the Docker image tag
        id: vars
        run: echo "TAG=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Build Docker Image
        run: |
          docker build -t ${{secrets.DOCKERHUB_USERNAME }}/frontend-app:${{env.TAG }} ./SayMyNameProjectFrontend 
          docker build -t ${{secrets.DOCKERHUB_USERNAME }}/backend-app:${{env.TAG }} ./backend

      # Step 5: Tag images for Docker Hub and AWS ECR
      - name: Tag Docker Images for both Docker Hub and AWS ECR
        run: |
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/frontend-app:${{ env.TAG }} ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/frontend-app:${{ env.TAG }}
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/backend-app:${{ env.TAG }} ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/backend-app:${{ env.TAG }}
          
      - name: Push to Docker
        run: |
          docker push ${{secrets.DOCKERHUB_USERNAME }}/frontend-app:${{env.TAG }}
          docker push ${{secrets.DOCKERHUB_USERNAME }}/backend-app:${{env.TAG }}

      - name: Using AWS Configure
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set region ${{ secrets.AWS_REGION }}

      - name: Log in to AWS ECR
        run: |
          aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | \
          docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com


      - name: Create frontend-app repository if it does not exist
        run: |
          aws ecr describe-repositories --repository-names frontend-app || aws ecr create-repository --repository-name frontend-app

      - name: Create backend-app repository if it does not exist
        run: |
          aws ecr describe-repositories --repository-names backend-app || aws ecr create-repository --repository-name backend-app

      - name: push to AWS ECR
        run: |
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/frontend-app:${{ env.TAG }}
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/backend-app:${{ env.TAG }}
      
