name: Build and push to Docker Hub and AWS ECR

on:
  push:
    branches:
      - main
jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3

        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}

      - name: Build Docker Image
        run: |
          docker build -t username/frontend-app:latest ./SayMyNameProjectFrontend 
          docker build -t username/backend-app:latest ./backend
      
